### ISSUE TITLE
squeeze doesn't move hotbar

### ISSUE THREAD

**Issue by altreflect** [xanthousm/MCXR#8]
squeezing the grips on my vive controllers doesn't move the hotbar :(

**Comment by xanthousm** [comment]
I haven't made changes to the vive control mapping since I first changed it, so I don't see anything that could have broken them. Do the grips work in one of the older releases? If they don't work in any of the releases, then we might just have to wait until the controller re-mapping update for MCXR from Sorenon comes out.

**Comment by xanthousm** [comment]
I found the change in 1.19 that broke the hotbar, it should be fixed now in the newest release. Thanks for reporting the bug!
